server_name: sase-nats-sandbox
listen: 0.0.0.0:4222
http: 0.0.0.0:8222

jetstream {
  store_dir: /data
  max_mem: 256MB
  max_file: 10GB
}

accounts {
  SASE {
    jetstream: enabled
    users = [
      { user: "admin", password: $NATS_ADMIN_PASS }

      {
        user: "pop01-pub"
        password: $NATS_POP01_PASS
        permissions: {
          publish:   { allow: ["security.alert.ids", "security.alert.proxy", "security.alert.dns", "security.alert.dlp", "security.alert.malware", "_INBOX.>"] }
          subscribe: { allow: ["_INBOX.>"] }
        }
      }

      {
        user: "mgmt01-pub"
        password: $NATS_MGMT01_PASS
        permissions: {
          publish:   { allow: ["security.alert.dlp", "identity.>", "_INBOX.>"] }
          subscribe: { allow: ["_INBOX.>"] }
        }
      }

      {
        user: "control-daemon"
        password: $NATS_DAEMON_PASS
        permissions: {
          publish:   { allow: ["_INBOX.>", "$JS.API.>", "$JS.ACK.>"] }
          subscribe: { allow: ["security.alert.>", "identity.>", "_INBOX.>", "$JS.API.>", "$JS.ACK.>"] }
        }
      }

      {
        user: "wazuh-forwarder"
        password: $NATS_WAZUH_PASS
        permissions: {
          publish:   { allow: ["_INBOX.>", "$JS.API.>", "$JS.ACK.>"] }
          subscribe: { allow: ["security.alert.>", "_INBOX.>", "$JS.API.>", "$JS.ACK.>"] }
        }
      }
    ]
  }
}

debug: false
trace: false
logtime: true
