# DLP ICAP Service - Python DLP server op mgmt01
icap_service svc_dlp_req reqmod_precache bypass=on icap://192.168.122.23:1345/dlpscan

# Alleen POST/PUT/PATCH verkeer naar DLP sturen
acl dlp_methods method POST PUT PATCH

# DLP-service activeren voor upload-verkeer van toegestane netwerken
adaptation_access svc_dlp_req allow dlp_methods localnet
adaptation_access svc_dlp_req allow dlp_methods subnets
adaptation_access svc_dlp_req deny all
icap_send_client_ip on
