
acl "loopback_only" { 127.0.0.1/32; };

options {

        directory       "/usr/local/etc/namedb/working";
        pid-file        "/var/run/named/pid";
        dump-file       "/var/dump/named_dump.db";
        statistics-file "/var/stats/named.stats";

        listen-on port 53530 { 127.0.0.1; };
        listen-on-v6 port 53530 { any; };



        allow-transfer {
                loopback_only;
        };


        max-cache-size    80%;
        dnssec-validation    no;
};

key "rndc-key" {
        algorithm "hmac-sha256";
        secret "VxtIzJevSQXqnr7h2qerrcwjnZlMWSGGFBndKeNIDfw=";
};
controls {
        inet 127.0.0.1 port 9530
                allow { 127.0.0.1; } keys { "rndc-key"; };
};

include "/usr/local/etc/namedb/named.conf.d/*.conf";

zone "." { type hint; file "/usr/local/etc/namedb/named.root"; };

zone "localhost"        { type primary; file "/usr/local/etc/namedb/primary/localhost-forward.db"; };
zone "127.in-addr.arpa" { type primary; file "/usr/local/etc/namedb/primary/localhost-reverse.db"; };
zone "0.ip6.arpa"       { type primary; file "/usr/local/etc/namedb/primary/localhost-reverse.db"; };


zone "threat-intel.rpz.sase" {
        type secondary;
        primaries { 192.168.122.23 key "tkey_rpz_transfer"; };
        allow-notify { 192.168.122.23; };
        file "/usr/local/etc/namedb/secondary/threat-intel.rpz.sase.db";
        allow-transfer {
                loopback_only;
        };
        allow-query {
                loopback_only;
        };
};
key "tkey_rpz_transfer" {
        algorithm "hmac-sha256";
        secret "HRcM/U+fm1mrj5pQQ4cvNmk7xtnddBWDkZl67fybnys=";
};


logging {
        channel default_log {
                file "/var/log/named/named.log" versions 3 size 5m;
                print-time yes;
                print-severity yes;
                print-category yes;
        };

        channel default_syslog {
                print-time yes;
                print-category yes;
                print-severity yes;
                syslog daemon;
                severity info;
        };

        channel query_log {
                file "/var/log/named/query.log" versions 3 size 5m;
                print-time yes;
        };

        channel rpz_log {
                file "/var/log/named/rpz.log" versions 3 size 5m;
                print-time yes;
        };

        category default { default_syslog; };
        category general { default_syslog; };
        category config { default_syslog; };
        category dispatch { default_syslog; };
        category network { default_syslog; };
        category queries { query_log; };
        category rpz { rpz_log; };
        category lame-servers { null; };
};

